site_name: Our Awesome Blog
site_description: A bloggin site built with Material for MkDocs
site_url: https://sitename.example
theme:
  name: material
  palette: 
  # Dark mode
  - scheme: slate
    toggle:
      icon: material/weather-sunny
      name: Dark mode
    primary: deep orange
    accent: deep purple
  
  # light mode
  - scheme: default
    toggle:
      icon: material/weather-night
      name: Light mode
    primary: blue
    accent: deep orange

plugins:
  - search
  - blog:
      blog_dir: .
      post_url_format: "{slug}"